# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e92b9bfd6d6ef786d4aee588aef18669abdb13aeed9567f2b77b0010bc6573a5caf82d6e5446d6c8facd216a765b2de636db2e8759ea3a93cb3d001c4e639cca

test:
  secret_key_base: e62fccd22f43bd49850c29cba014bd03e985d05771fb0455048749f1d42e33930240ecc42e9f9ac1b518ba1a88fb39da137e3bcbf718b54b92b2971f80d9dd54

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
